### ISSUE TITLE
Improve the security of IAM roles for AWS

### ISSUE THREAD

**Issue by aaronmell** [AviatrixSystems/Docs#116]
The policy requirements are too broad.
https://docs.aviatrix.com/HowTos/aviatrix_iam_policy_requirements.html

For example
 iam:get*
Do you really need access to these things?
"iam:GetAccountPasswordPolicy",
"iam:ListVirtualMFADevices",
"iam:GetOrganizationsAccessReport",
"iam:GetAccountAuthorizationDetails",
"iam:GetCredentialReport"

Also the policy should attempt to limit the scope to aviatrix resources via conditions or resource level persmissions

**Comment by SamGforce** [comment]
We have enhanced the policy requirements. Please refer to the same link
