### ISSUE TITLE
What is the "onboarding process"?

### ISSUE THREAD

**Issue by patrickjburke245** [AviatrixSystems/Docs#733]
The first question on [Onboarding and Account FAQs](https://docs.aviatrix.com/HowTos/onboarding_faq.html) is _**Where do I Start?**_. It mentions an onboarding process but no further details or visuals are provided. I'd suggest either deleting the section or elaborating on what the onboarding process looks like.

**Comment by brendaroldan** [comment]
Thank you for pointing that out Patrick. Information was added for the Where do I Start question
